### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by alesolano**
Some update to the C++ file.

It works, but the node shuts down after getting a good result from the server. This is not awful, but it makes the feedback_callback not to run completely.

Tried to use some OOP like all _v2 nodes in this repo, but its not working. **In fact, not even the [official ROS2 examples](https://github.com/ros2/examples/tree/master/rclcpp/minimal_action_client) regarding actions compile**. It seems that there's some work still to do with actions in ROS2.

Tried also to replicate [python actions](https://github.com/ros2/examples/blob/master/rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client.py)... also not working

### CODE REVIEW

**Comment by ahcorde** [comment]
they are pushing code for dashing not for cyrstal. Maybe that's why is not compiling.

**Comment by rkojcev** [comment]
I also saw the same. I am not sure if actions are complete in Crystal.

**Comment by ahcorde** [comment]
can you check that this is working with the dashing release?

**Comment by alesolano** [comment]
Sure, i'll check it

**Comment by alesolano** [comment]
Publishers, subscribers and actions working on the `dashing` branch.

**Comment by alesolano** [comment]
Well, this still happens:
> It works, but the node shuts down after getting a good result from the server. This is not awful, but it makes the feedback_callback not to run completely.

So MARA completes the trajectory but the `ROS_INFOs` after [this line](https://github.com/AcutronicRobotics/mara_examples/blob/dashing/mara_minimal_trajectory_action/src/mara_minimal_trajectory_action.cpp#L33) in the feedback callback and after [this line](https://github.com/AcutronicRobotics/mara_examples/blob/dashing/mara_minimal_trajectory_action/src/mara_minimal_trajectory_action.cpp#L135) in main are not printed.

-------

This won't solve the issue, but I will try to integrate the new [result callback](https://github.com/ros2/rclcpp/blob/ef41059a751702274667e2164182c062b47c453d/rclcpp_action/include/rclcpp_action/client.hpp#L281) to wrap up [these lines](https://github.com/AcutronicRobotics/mara_examples/blob/dashing/mara_minimal_trajectory_action/src/mara_minimal_trajectory_action.cpp#L119-L152).

**Comment by alesolano** [comment]
I'm updating everything in crystal as well. Closing this.

**Pull request closed without merging**
