### PR TITLE
Update mara examples

### PR DESCRIPTION
**Pull request by alesolano**
Update mara examples with new topic names, more comments and more simplicity.
Maybe I'll add more examples in which we adapt a more OOP-fashion for creating nodes.

### CODE REVIEW

**Comment by alesolano** [comment]
Subscribers get stuck at spin() and don't jump to callback

EDIT: Solved! Thanks @nzlz

**Comment by alesolano** [comment]
Publishers, subscribers and python service work. The rest is still untested/not working.

EDIT: c++ service also working

**Comment by alesolano** [comment]
Added new versions (defining nodes as classes, with callbacks as methods of this class) for publishers and subscribers

**Comment by alesolano** [comment]
Added new versions for clients.

A few things:
1. I still need to review the [actions](https://github.com/alesolano/mara_examples/tree/master/mara_minimal_trajectory_action)
2. I think that [gripper subscriber](https://github.com/AcutronicRobotics/mara_examples/tree/master/gripper_minimal_subscriber) may not be very necessary since we have already an example of a subscriber for the MARA joints.

Apart from those two points, I'm OK with everything else. I'm going to remove the WIP tag of the PR. You can merge it if considered appropriate.

**Comment by alesolano** [comment]
Assigning to review @ahcorde  @rkojcev @YueErro

(I can't assign since this is a fork)

**Comment by YueErro** [comment]
Will review tomorrow.

**Review by ahcorde — APPROVED** [review]

**Review by LanderU — APPROVED** [review]

**Comment by rkojcev** [comment]
Tested this works fine. Great job @alesolano . The example for mara_minimal_trajectory_action will come with another PR.

Merging this

**Pull request merged**
